name: RemoteCommands

# Trigger on push to master
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_DISCORD_CAS }}
      - name: SSH to remote server and run command
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_ADDR }} "date > ~/date.txt"
